# Data Visualization Deception Project - Derek Thomas - 17Nov2017

### Argument Framework - Visualization

Claim
- The decrease in US College enrollment among Whites is not due to college admittance practices 

Warrant
- Since there is a corresponding decrease in Whites as a percentage of total population

Evidence
- College Scorecard, Department of Education, ED.gov, 2015-2016 Dataset
Reference: https://catalog.data.gov/dataset/college-scorecard
- Population data set - American Fact Finder American Community Survery (ACS) 
Reference: https://factfinder.census.gov 

Audience
- College Admissions Offices
- Government Financial Aid Boards
Audience Needs
- Enrollment statistics
- Planning Data

Metrics
- Percentage of various Ethnic Group college enrollment as a percentage of Total College Enrollment
- Percentage of various Ethnic Group populations as a percentage of Total Population

### Argument Framework - Deception

Claim
- The decrease in US College enrollment among Whites from 2011-2016 is due to the admittance of Hispanics over Whites 

Warrant
- Since there is a decrease in college enrollment among Whites from 2011-2016, and an increase in enrollment among Hispanics during the same period, one must be the causation of the other.

Evidence
- College Scorecard, Department of Education, ED.gov, 2015-2016 Dataset
Reference: https://catalog.data.gov/dataset/college-scorecard

Audience
- White Nationalist
- White Supremacist
- Alt-Right Movement
- President Trumps supporter base
Audience Needs
- Power
- Control
Audience Wants
- Species purity
Audience Fears
- Loss of identity
- Loss of Country

Metrics
- Total decresee in College Enrollment amongst Whites
- Total losses of rights/benefits to Whites at the expense/gain of non-Whites

## The Deception

The Deception here involves utilizing College enrollment data from the US Department of Education to highlight a decrease in college enrollment among Whites from 2011-2016 compared to an increase in college enrollmentt among Hispanics during the same period. The visualization attempts to influcence the audience through data that one is a reslut of the other. The real visualization disproves this by showing that the decrease in enrollment among Whites is more likely attributable to the corresponding decrease in the Population percentage of Whites to non-Whites over the same period.

## Define the environment for the Dataframe

In [26]:
import pandas as pd
import numpy as np
import urllib3
http = urllib3.PoolManager()
import string
import re
import json
from collections import OrderedDict
import warnings
warnings.filterwarnings('ignore')

## Import the referenced raw Dept of Education source data

In [27]:
columnsToInclude =['UNITID',    # Unit ID for institution
                   'INSTNM',      # Institution name
                   'CITY',        # City
                   'STABBR',      # State postcode
                   'ZIP',         # ZIP code
                   'HIGHDEG',     # Highest degree awarded: 0-Non Degree;1-Certificate;2-Associate;3-Bachelor's;4-Graduate
                   'CONTROL',     # Control of institution: 1-Public;2-Private nonprofit;3-Private for-profit
                   'REGION',      # Region: 1-New England;2-Mid Ease;3-Great Lakes;4-Plains;5-Southease;6-Southwest;7-Rocky Mountains;8-Far West;9-Outlying Areas
                   'LATITUDE',    # Latitude (Decimal)
                   'LONGITUDE',   # Longitude (Decimal)
                   'CCUGPROF',    # Carnegie Classification - undergraduate profile: >= 5 for Four-year programs
                   'ADM_RATE',    # Admission Rate
                   'ACTCMMID',    # Midpoint of the ACT cumulative score
                   'SAT_AVG',     # Average SAT equivalent score of students admitted
                   'UG',          # Enrollment - All
                   'UGDS_WHITE',  # Enrollment - White
                   'UGDS_BLACK',  # Enrollment - Black
                   'UGDS_HISP',   # Enrollment - Hispanic
                   'UGDS_ASIAN',  # Enrollment - Asian
                   'UGDS_AIAN',   # Enrollment - American Indian/Alaska Native
                   'UGDS_NHPI',   # Enrollment - Native Hawaiian/Pacific Islander
                   'UGDS_2MOR',   # Enrollment - Two or more Races
                   'UGDS_NRA',    # Enrollment - Non-Resident Aliens
                   'UGDS_UNKN',   # Enrollment - Race Unknown
                   'COSTT4_A',    # Average cost of attendance (academic year institutions)
                   'COSTT4_P',    # Average cost of attendance (program-year institutions)
                   'LOAN_EVER',   # Share of students who received a Federal Loan while in school
                   'PELL_EVER',   # Share of students who received a pELL gRANT while in school
                   'PCTPELL']     # Percentage of undergraduates who receive a Pell Grant

### Read in source csv value, only retrieving applicable columns from data set

In [28]:
dfSchools = (pd.read_csv('MERGED2010_11_PP.csv', header=0, usecols=(columnsToInclude)))
dfSchools['SchoolYear'] = '2010-2011'

In [29]:
dfSchools.head(4)

,UNITID,INSTNM,CITY,STABBR,ZIP,HIGHDEG,CONTROL,REGION,LATITUDE,LONGITUDE,...,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,COSTT4_A,COSTT4_P,PCTPELL,LOAN_EVER,PELL_EVER,SchoolYear
0,100654,Alabama A & M University,Normal,AL,35762,4,1,5,NaN,NaN,...,0.0000,0.0000,0.0087,0.0041,13762.0,NaN,0.6317,0.9382239382,0.8563706564,2010-2011
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,4,1,5,NaN,NaN,...,0.0008,0.0114,0.0178,0.0344,18003.0,NaN,0.2882,0.9136452242,0.6183235867,2010-2011
2,100690,Amridge University,Montgomery,AL,36117-3553,4,2,5,NaN,NaN,...,0.0000,0.0000,0.0000,0.2730,20700.0,NaN,0.5816,0.9351032448,0.8554572271,2010-2011
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,4,1,5,NaN,NaN,...,0.0002,0.0153,0.0278,0.0177,17064.0,NaN,0.2750,0.9064138766,0.6639774102,2010-2011

In [30]:
dfTemp = pd.read_csv('MERGED2011_12_PP.csv', header=0, usecols=(columnsToInclude))
dfTemp['SchoolYear'] = '2011-2012'
dfSchools = dfSchools.append(dfTemp)

In [31]:
dfTemp = pd.read_csv('MERGED2012_13_PP.csv', header=0, usecols=(columnsToInclude))
dfTemp['SchoolYear'] = '2012-2013'
dfSchools = dfSchools.append(dfTemp)

In [32]:
dfTemp = pd.read_csv('MERGED2013_14_PP.csv', header=0, usecols=(columnsToInclude))
dfTemp['SchoolYear'] = '2013-2014'
dfSchools = dfSchools.append(dfTemp)

In [33]:
dfTemp = pd.read_csv('MERGED2014_15_PP.csv', header=0, usecols=(columnsToInclude))
dfTemp['SchoolYear'] = '2014-2015'
dfSchools = dfSchools.append(dfTemp)

In [34]:
dfTemp = pd.read_csv('MERGED2015_16_PP.csv', header=0, usecols=(columnsToInclude))
dfTemp['SchoolYear'] = '2015-2016'
dfSchools = dfSchools.append(dfTemp)

In [35]:
dfSchools['Year'] = dfSchools['SchoolYear'].str[5:9]

In [36]:
len(dfSchools)

45982

In [37]:
dfSchools.columns

Index([u'UNITID', u'INSTNM', u'CITY', u'STABBR', u'ZIP', u'HIGHDEG',
       u'CONTROL', u'REGION', u'LATITUDE', u'LONGITUDE', u'CCUGPROF',
       u'ADM_RATE', u'ACTCMMID', u'SAT_AVG', u'UG', u'UGDS_WHITE',
       u'UGDS_BLACK', u'UGDS_HISP', u'UGDS_ASIAN', u'UGDS_AIAN', u'UGDS_NHPI',
       u'UGDS_2MOR', u'UGDS_NRA', u'UGDS_UNKN', u'COSTT4_A', u'COSTT4_P',
       u'PCTPELL', u'LOAN_EVER', u'PELL_EVER', u'SchoolYear', u'Year'],
      dtype='object')

In [38]:
dfSchools.head(2)

,UNITID,INSTNM,CITY,STABBR,ZIP,HIGHDEG,CONTROL,REGION,LATITUDE,LONGITUDE,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,COSTT4_A,COSTT4_P,PCTPELL,LOAN_EVER,PELL_EVER,SchoolYear,Year
0,100654,Alabama A & M University,Normal,AL,35762,4,1,5.0,NaN,NaN,...,0.0000,0.0087,0.0041,13762.0,NaN,0.6317,0.9382239382,0.8563706564,2010-2011,2011
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,4,1,5.0,NaN,NaN,...,0.0114,0.0178,0.0344,18003.0,NaN,0.2882,0.9136452242,0.6183235867,2010-2011,2011

In [39]:
dfSchools.columns=(['Unit ID',\
            'Institution Name',\
            'City',\
            'State',\
            'Zip Code',\
            'High Degree',\
            'Institution Type',\
            'Region ID',\
            'Latitude',\
            'Longitude',\
            'Program Type',\
            'Admission Rate',\
            'ACT Score',\
            'SAT Average',\
            'Enrollment',\
            'White',\
            'Black',\
            'Hispanic',\
            'Asian',\
            'American Indian/Alaska Native',\
            'Native Hawaiian/Pacific Islander',\
            'Multi-Racial',\
            'Non-Resident Aliens',\
            'Race Unknown',\
            'Attendance Cost - Academic Yr',\
            'Attendance Cost - Program Yr',\
            'Pell Grant Pct',\
            'Student Loan Pct',\
            'Pell Grant Award Pct',\
            'School Year',
            'Year'])
dfSchools.head(2)

,Unit ID,Institution Name,City,State,Zip Code,High Degree,Institution Type,Region ID,Latitude,Longitude,...,Multi-Racial,Non-Resident Aliens,Race Unknown,Attendance Cost - Academic Yr,Attendance Cost - Program Yr,Pell Grant Pct,Student Loan Pct,Pell Grant Award Pct,School Year,Year
0,100654,Alabama A & M University,Normal,AL,35762,4,1,5.0,NaN,NaN,...,0.0000,0.0087,0.0041,13762.0,NaN,0.6317,0.9382239382,0.8563706564,2010-2011,2011
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,4,1,5.0,NaN,NaN,...,0.0114,0.0178,0.0344,18003.0,NaN,0.2882,0.9136452242,0.6183235867,2010-2011,2011

Adjust "Student Loan Pct" & "Pell Grant Award Pct" columns to replace "PrivacySuppressed" text with Null values

In [40]:
dfSchools['Student Loan Pct'] = dfSchools['Student Loan Pct'].replace('PrivacySuppressed',np.nan)
dfSchools['Pell Grant Award Pct'] = dfSchools['Pell Grant Award Pct'].replace('PrivacySuppressed',np.nan)

In [41]:
dfSchools['Student Loan Pct'] = pd.to_numeric(dfSchools['Student Loan Pct'])
dfSchools['Pell Grant Award Pct'] = pd.to_numeric(dfSchools['Pell Grant Award Pct'])

In [42]:
dfSchools[(~(dfSchools['Student Loan Pct'] > 0)) | (~(dfSchools['Student Loan Pct'].isnull()))]

,Unit ID,Institution Name,City,State,Zip Code,High Degree,Institution Type,Region ID,Latitude,Longitude,...,Multi-Racial,Non-Resident Aliens,Race Unknown,Attendance Cost - Academic Yr,Attendance Cost - Program Yr,Pell Grant Pct,Student Loan Pct,Pell Grant Award Pct,School Year,Year
0,100654,Alabama A & M University,Normal,AL,35762,4,1,5.0,NaN,NaN,...,0.0000,0.0087,0.0041,13762.0,NaN,0.6317,0.938224,0.856371,2010-2011,2011
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,4,1,5.0,NaN,NaN,...,0.0114,0.0178,0.0344,18003.0,NaN,0.2882,0.913645,0.618324,2010-2011,2011
2,100690,Amridge University,Montgomery,AL,36117-3553,4,2,5.0,NaN,NaN,...,0.0000,0.0000,0.2730,20700.0,NaN,0.5816,0.935103,0.855457,2010-2011,2011
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,4,1,5.0,NaN,NaN,...,0.0153,0.0278,0.0177,17064.0,NaN,0.2750,0.906414,0.663977,2010-2011,2011
4,100724,Alabama State University,Montgomery,AL,36104-0271,4,1,5.0,NaN,NaN,...,0.0004,0.0051,0.0256,14390.0,NaN,0.7439,0.924936,0.908715,2010-2011,2011
5,100751,The University of Alabama,Tuscaloosa,AL,35487-0166,4,1,5.0,NaN,NaN,...,0.0053,0.0115,0.0023,21565.0,NaN,0.2073,0.941295,0.567328,2010-2011,2011
6,100760,Central Alabama Community College,Alexander City,AL,35010,2,1,5.0,NaN,NaN,...,0.0000,0.0004,0.0064,7109.0,NaN,0.5481,0.519462,0.929841,2010-2011,2011
7,100812,Athens State University,Athens,AL,35611,3,1,5.0,NaN,NaN,...,0.0000,0.0064,0.0205,NaN,NaN,0.3530,0.807887,0.746208,2010-2011,2011
8,100830,Auburn University at Montgomery,Montgomery,AL,36117-3596,4,1,5.0,NaN,NaN,...,0.0000,0.0301,0.0330,14367.0,NaN,0.3542,0.922756,0.733820,2010-2011,2011
9,100858,Auburn University,Auburn,AL,36849,4,1,5.0,NaN,NaN,...,0.0000,0.0067,0.0108,19490.0,NaN,0.1538,0.930955,0.481186,2010-2011,2011
10,100937,Birmingham Southern College,Birmingham,AL,35254,4,2,5.0,NaN,NaN,...,0.0171,0.0000,0.0072,38205.0,NaN,0.2115,0.959184,0.495362,2010-2011,2011
11,101028,Chattahoochee Valley Community College,Phenix City,AL,36869,2,1,5.0,NaN,NaN,...,0.0077,0.0019,0.0251,5540.0,NaN,0.5179,0.067051,NaN,2010-2011,2011
12,101073,Concordia College Alabama,Selma,AL,36701,3,2,5.0,NaN,NaN,...,0.0000,0.0245,0.0000,13210.0,NaN,0.9236,0.863772,0.973054,2010-2011,2011
13,101116,South University-Montgomery,Montgomery,AL,36116,4,3,5.0,NaN,NaN,...,0.0134,0.0000,0.0000,27418.0,NaN,0.8097,0.857817,0.856475,2010-2011,2011
14,101143,Enterprise State Community College,Enterprise,AL,36330-1300,2,1,5.0,NaN,NaN,...,0.0102,0.0020,0.0149,9146.0,NaN,0.4144,0.460653,0.888173,2010-2011,2011
15,101161,James H Faulkner State Community College,Bay Minette,AL,36507-2698,2,1,5.0,NaN,NaN,...,0.0106,0.0007,0.0047,7987.0,NaN,0.4278,0.540830,0.850248,2010-2011,2011
16,101189,Faulkner University,Montgomery,AL,36109-3390,4,2,5.0,NaN,NaN,...,0.0069,0.0141,0.4049,24105.0,NaN,0.7654,0.935857,0.818708,2010-2011,2011
17,101240,Gadsden State Community College,Gadsden,AL,35903,2,1,5.0,NaN,NaN,...,0.0100,0.0159,0.0061,9628.0,NaN,0.5126,NaN,NaN,2010-2011,2011
18,101286,George C Wallace State Community College-Dothan,Dothan,AL,36303-9234,2,1,5.0,NaN,NaN,...,0.0063,0.0009,0.0044,7168.0,NaN,0.5096,NaN,NaN,2010-2011,2011
19,101295,George C Wallace State Community College-Hance...,Hanceville,AL,35077-2000,2,1,5.0,NaN,NaN,...,0.0055,0.0057,0.0018,9743.0,NaN,0.4525,0.644220,0.851178,2010-2011,2011
20,101301,George C Wallace State Community College-Selma,Selma,AL,36703-2808,2,1,5.0,NaN,NaN,...,0.0021,0.0000,0.0021,14339.0,NaN,0.7265,NaN,NaN,2010-2011,2011
21,101365,Herzing University-Birmingham,Birmingham,AL,35209,3,3,5.0,NaN,NaN,...,0.0387,0.0000,0.0218,21272.0,NaN,0.7318,0.828715,0.884310,2010-2011,2011
22,101435,Huntingdon College,Montgomery,AL,36106-2148,3,2,5.0,NaN,NaN,...,0.0119,0.0064,0.1481,28724.0,NaN,0.3498,0.938659,0.614836,2010-2011,2011
23,101453,Heritage Christian University,Florence,AL,35630-9977,4,2,5.0,NaN,NaN,...,0.0000,0.0000,0.0000,14639.0,NaN,0.6164,NaN,NaN,2010-2011,2011
24,101462,J F Drake State Community and Technical College,Huntsville,AL,35811,2,1,5.0,NaN,NaN,...,0.0072,0.0096,0.0032,10428.0,NaN,0.6590,NaN,NaN,2010-2011,2011
25,101480,Jacksonville State University,Jacksonville,AL,36265,4,1,5.0,NaN,NaN,...,0.0000,0.0234,0.0330,16378.0,NaN,0.4174,0.903579,0.756461,2010-2011,2011
26,101499,Jefferson Davis Community College,Brewton,AL,36426,2,1,5.0,NaN,NaN,...,0.0088,0.0000,0.0565,7359.0,NaN,0.5464,NaN,NaN,2010-2011,2011
27,101505,Jefferson State Community College,Birmingham,AL,35215-3098,2,1,5.0,NaN,NaN,...,0.0221,0.0092,0.0009,12048.0,NaN,0.2022,0.513301,0.834957,2010-2011,2011
28,101514,John C Calhoun State Community College,Tanner,AL,35671,2,1,5.0,NaN,NaN,...,0.0245,0.0041,0.0084,8937.0,NaN,0.3428,0.500909,0.868476,2010-2011,2011
29,101541,Judson College,Marion,AL,36756,3,2,5.0,NaN,NaN,...,0.0290,0.0032,0.0000,24537.0,NaN,0.4121,0.930851,0.632979,2010-2011,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7563,45891902,Strayer University-Morrow Campus,Morrow,GA,30260,0,3,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7564,45891903,Strayer University-Roswell Campus,Roswell,GA,30076,0,3,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7565,45891904,Strayer University-Douglasville Campus,Douglasville,GA,30135,0,3,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7566,45891905,Strayer University-Lithonia Campus,Lithonia,GA,30038,0,3,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7567,45891906,Strayer University-Savannah Campus,Savannah,GA,31419,0,3,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7568,45891907,Strayer University-Augusta Campus,Augusta,GA,30909,0,3,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7569,45891908,Strayer University-Columbus,Columbus,GA,31909,0,3,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7570,45896401,Strayer University-Columbia Campus,Columbia,SC,29210,0,3,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7571,45896402,Strayer University-Charleston Campus,North Charleston,SC,29418,0,3,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7572,45897301,Strayer University-Irving,Irving,TX,75063,0,3,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7573,45897302,Strayer University-Katy,Houston,TX,77079,0,3,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7574,45897303,Strayer University-Northwest Houston,Houston,TX,77064,0,3,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7575,45897304,Strayer University-Plano,Plano,TX,75093,0,3,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7576,45897305,Strayer University-Cedar Hill,Cedar Hill,TX,75104,0,3,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7577,45897306,Strayer University-North Dallas,Dallas,TX,75251,0,3,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7578,45897307,Strayer University-San Antonio,San Antonio,TX,78216,0,3,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7579,45897308,Strayer University-Stafford,Stafford,TX,77477,0,3,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.907506,0.858398,2015-2016,2016
7580,45920401,Unitek College,Fremont,CA,945383185,0,3,8.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.910320,0.704371,2015-2016,2016
7581,47503301,Relay Graduate School of Education - Newark,Newark,NJ,71023106,0,2,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-2016,2016
7582,47503302,Relay Graduate School of Education - New Orleans,New Orleans,LA,701123701,0,2,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-2016,2016
7583,47647001,WestMed College - Merced,Merced,CA,953400000,0,2,8.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.868132,0.791209,2015-2016,2016
7584,47657701,Vantage College,El Paso,TX,799064951,0,3,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.895189,0.924399,2015-2016,2016
7585,47657702,Vantage College,Austin,TX,787523733,0,3,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.895189,0.924399,2015-2016,2016
7586,47691101,SAE Institute of Technology San Francisco,Emeryville,CA,94608,0,3,8.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.886598,0.734536,2015-2016,2016
7587,48065701,Rasmussen College - Overland Park,Overland Park,KS,662102786,0,3,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.900435,0.749718,2015-2016,2016
7588,48154401,National Personal Training Institute of Cleveland,Highland Heights,OH,44143,0,3,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.684211,2015-2016,2016
7589,48387801,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,951131820,0,3,8.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.774725,0.901099,2015-2016,2016
7590,48400201,High Desert Medical College,Lancaster,CA,935340000,0,3,8.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.904564,0.940526,2015-2016,2016
7591,48414501,Vantage College-San Antonio,San Antonio,TX,782211361,0,3,6.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.928571,0.841270,2015-2016,2016
7592,48621101,American Institute of Pharmaceutical Technolog...,Newark,NJ,7102,0,3,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-2016,2016

In [43]:
dfSchoolSummary = dfSchools.groupby(by=['State', 'Year'], as_index=False).mean()
dfSchoolSummary

,State,Year,Unit ID,High Degree,Institution Type,Region ID,Latitude,Longitude,Program Type,Admission Rate,...,American Indian/Alaska Native,Native Hawaiian/Pacific Islander,Multi-Racial,Non-Resident Aliens,Race Unknown,Attendance Cost - Academic Yr,Attendance Cost - Program Yr,Pell Grant Pct,Student Loan Pct,Pell Grant Award Pct
0,AK,2011,1.774609e+05,2.555556,1.444444,8.0,NaN,NaN,NaN,0.332850,...,0.304122,0.008489,0.031544,0.007911,0.092556,18468.666667,11332.500000,0.279056,0.753481,0.702259
1,AK,2012,1.699728e+05,2.700000,1.500000,8.0,NaN,NaN,NaN,0.345750,...,0.286300,0.005490,0.029130,0.006330,0.080450,17199.000000,19440.000000,0.304110,0.736423,0.717531
2,AK,2013,1.699728e+05,2.700000,1.500000,8.0,NaN,NaN,NaN,0.603400,...,0.264530,0.008290,0.043300,0.006750,0.126580,16559.375000,19111.500000,0.314130,0.738735,0.715001
3,AK,2014,1.699728e+05,2.800000,1.500000,8.0,NaN,NaN,NaN,0.431650,...,0.250370,0.006600,0.047280,0.007150,0.129970,18669.000000,17095.000000,0.328830,0.723023,0.717636
4,AK,2015,1.773741e+05,3.000000,1.555556,8.0,NaN,NaN,NaN,0.420700,...,0.264989,0.011378,0.048800,0.005811,0.105044,19233.428571,19659.000000,0.346067,0.705379,0.730090
5,AK,2016,1.773741e+05,2.888889,1.555556,8.0,62.258589,-148.702003,5.333333,0.578800,...,0.267100,0.012311,0.048044,0.009856,0.100167,18905.000000,19227.000000,0.331367,0.669976,0.718552
6,AL,2011,1.165462e+06,2.568182,1.795455,5.0,NaN,NaN,NaN,0.659031,...,0.006020,0.000782,0.005894,0.006645,0.046648,17375.594203,20935.818182,0.552573,0.824205,0.802519
7,AL,2012,1.131187e+06,2.489130,1.836957,5.0,NaN,NaN,NaN,0.694635,...,0.006121,0.000811,0.007203,0.007101,0.049034,18138.929577,14607.727273,0.584438,0.822684,0.817416
8,AL,2013,1.213252e+06,2.463158,1.852632,5.0,NaN,NaN,NaN,0.703462,...,0.005284,0.001051,0.008379,0.006752,0.063534,19152.493151,15882.833333,0.607458,0.835178,0.811159
9,AL,2014,1.205624e+06,2.458333,1.864583,5.0,NaN,NaN,NaN,0.719052,...,0.005529,0.001104,0.010741,0.007467,0.045287,19630.561644,16743.357143,0.596058,0.833811,0.804615
10,AL,2015,1.198476e+06,2.432990,1.865979,5.0,NaN,NaN,NaN,0.708681,...,0.006164,0.001660,0.012502,0.008368,0.040071,19982.671233,16375.071429,0.605278,0.817302,0.800039
11,AL,2016,1.206031e+06,2.489583,1.854167,5.0,32.825485,-86.833524,5.011111,0.671275,...,0.006280,0.000966,0.015251,0.009460,0.032002,20521.916667,18361.000000,0.592458,0.803047,0.779433
12,AR,2011,1.080528e+06,1.965909,2.045455,5.0,NaN,NaN,NaN,0.684077,...,0.006896,0.000752,0.007728,0.011755,0.017170,17268.490566,21146.038462,0.550187,0.746285,0.837195
13,AR,2012,1.071167e+06,1.933333,2.055556,5.0,NaN,NaN,NaN,0.681054,...,0.006946,0.001168,0.010824,0.010442,0.023768,17906.962264,14366.533333,0.594393,0.757359,0.839022
14,AR,2013,9.539135e+05,1.988889,2.044444,5.0,NaN,NaN,NaN,0.691032,...,0.006143,0.001128,0.013983,0.012219,0.033584,18642.962264,15537.689655,0.579818,0.755986,0.832233
15,AR,2014,1.075100e+06,2.011236,2.033708,5.0,NaN,NaN,NaN,0.659673,...,0.008095,0.001114,0.017215,0.011083,0.022913,18249.370370,15886.666667,0.587865,0.748601,0.826185
16,AR,2015,1.194212e+06,1.966292,2.033708,5.0,NaN,NaN,NaN,0.705982,...,0.009208,0.001327,0.018067,0.010875,0.013924,18351.076923,16872.178571,0.584073,0.764318,0.830452
17,AR,2016,1.284176e+06,1.923913,2.043478,5.0,35.021922,-92.582857,3.141176,0.695177,...,0.010173,0.002566,0.018467,0.010412,0.019665,18865.961538,16962.733333,0.564407,0.737194,0.814476
18,AS,2011,2.407360e+05,2.000000,1.000000,9.0,NaN,NaN,NaN,NaN,...,0.000500,0.914300,0.000000,0.075700,0.001400,4520.000000,NaN,0.965300,NaN,NaN
19,AS,2012,2.407360e+05,2.000000,1.000000,9.0,NaN,NaN,NaN,NaN,...,0.000000,0.924000,0.000000,0.069800,0.000500,5040.000000,NaN,0.736900,NaN,NaN
20,AS,2013,2.407360e+05,3.000000,1.000000,9.0,NaN,NaN,NaN,NaN,...,0.000000,0.913100,0.000000,0.076900,0.000000,5180.000000,NaN,0.692500,NaN,NaN
21,AS,2014,2.407360e+05,3.000000,1.000000,9.0,NaN,NaN,NaN,NaN,...,0.000000,0.917300,0.000000,0.068600,0.001300,6410.000000,NaN,0.509200,NaN,NaN
22,AS,2015,2.407360e+05,3.000000,1.000000,9.0,NaN,NaN,NaN,NaN,...,0.000000,0.919300,0.000000,0.072100,0.002400,6560.000000,NaN,0.724500,NaN,NaN
23,AS,2016,2.407360e+05,3.000000,1.000000,9.0,-14.322587,-170.742728,5.000000,NaN,...,0.000000,0.897300,0.000000,0.092600,0.000000,7526.000000,NaN,0.809600,NaN,NaN
24,AZ,2011,2.499393e+05,2.104000,2.480000,6.0,NaN,NaN,NaN,0.720800,...,0.062428,0.004266,0.020845,0.014086,0.087933,21593.370370,28427.666667,0.517402,0.816443,0.831593
25,AZ,2012,2.640669e+05,2.134328,2.529851,6.0,NaN,NaN,NaN,0.762571,...,0.061283,0.005103,0.024554,0.006467,0.089616,22423.982759,19328.622951,0.542898,0.827276,0.846147
26,AZ,2013,2.712813e+05,2.148148,2.525926,6.0,NaN,NaN,NaN,0.819295,...,0.064445,0.004156,0.022827,0.007134,0.107726,21604.216667,20139.274194,0.544764,0.817904,0.846852
27,AZ,2014,2.769553e+05,2.226277,2.467153,6.0,NaN,NaN,NaN,0.820464,...,0.063306,0.005400,0.027777,0.009242,0.097314,21898.468750,20273.180328,0.557751,0.803605,0.835454
28,AZ,2015,2.848044e+05,2.203008,2.443609,6.0,NaN,NaN,NaN,0.803738,...,0.062478,0.005348,0.029874,0.006382,0.085420,21644.590164,20351.540984,0.552417,0.792512,0.823011
29,AZ,2016,3.732344e+05,2.195489,2.421053,6.0,33.399975,-111.841310,2.560606,0.808000,...,0.061349,0.004360,0.027852,0.006999,0.094519,21608.633333,21340.754098,0.550115,0.779669,0.796765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,VT,2011,2.234214e+06,2.935484,1.903226,1.0,NaN,NaN,NaN,0.750278,...,0.004732,0.001084,0.013276,0.012800,0.075004,33299.105263,26342.400000,0.360112,0.937439,0.573390
325,VT,2012,2.234214e+06,2.903226,1.903226,1.0,NaN,NaN,NaN,0.773200,...,0.004532,0.004448,0.021036,0.013472,0.077588,34307.421053,20318.800000,0.393364,0.930066,0.593196
326,VT,2013,2.293872e+06,2.966667,1.933333,1.0,NaN,NaN,NaN,0.777761,...,0.005046,0.005246,0.023017,0.013433,0.095162,35904.789474,21671.250000,0.372904,0.921697,0.589582
327,VT,2014,2.364322e+06,3.068966,1.896552,1.0,NaN,NaN,NaN,0.790106,...,0.008165,0.010217,0.020896,0.018300,0.078561,37510.000000,23056.000000,0.388991,0.914421,0.578950
328,VT,2015,1.712051e+06,3.178571,1.892857,1.0,NaN,NaN,NaN,0.783328,...,0.004500,0.001209,0.021070,0.022757,0.070843,38616.210526,23611.666667,0.352904,0.903580,0.574941
329,VT,2016,1.766911e+06,3.148148,1.888889,1.0,43.897245,-72.838455,8.440000,0.734894,...,0.006378,0.000783,0.023461,0.022974,0.072496,39753.944444,23495.333333,0.359877,0.897940,0.539068
330,WA,2011,9.528216e+05,2.208000,2.040000,8.0,NaN,NaN,NaN,0.674087,...,0.023057,0.007634,0.031313,0.014991,0.076972,20803.076923,25319.083333,0.401343,0.748061,0.755535
331,WA,2012,1.209505e+06,2.170543,2.046512,8.0,NaN,NaN,NaN,0.725328,...,0.023321,0.008754,0.038478,0.018219,0.068034,21138.844156,17798.864865,0.436816,0.738691,0.769091
332,WA,2013,1.203886e+06,2.269231,2.053846,8.0,NaN,NaN,NaN,0.710997,...,0.023686,0.009011,0.045069,0.021340,0.071136,21583.857143,18234.500000,0.462050,0.726271,0.773215
333,WA,2014,1.224129e+06,2.291339,2.023622,8.0,NaN,NaN,NaN,0.798577,...,0.021902,0.009673,0.051466,0.024405,0.064194,22469.128205,18109.600000,0.449857,0.726462,0.766608
334,WA,2015,1.220298e+06,2.281250,2.023438,8.0,NaN,NaN,NaN,0.800294,...,0.020562,0.009882,0.053782,0.022584,0.076897,23126.797468,18350.764706,0.446662,0.718527,0.760114
335,WA,2016,1.066500e+06,2.330709,1.976378,8.0,47.488310,-121.673606,4.196721,0.762845,...,0.023644,0.010376,0.060776,0.024571,0.064229,23388.894737,19019.457143,0.443479,0.701032,0.738107
336,WI,2011,1.085391e+06,2.431034,2.155172,3.0,NaN,NaN,NaN,0.763700,...,0.023978,0.000793,0.010220,0.007768,0.061709,22260.722222,30070.333333,0.435011,0.892506,0.700851
337,WI,2012,1.180785e+06,2.459016,2.213115,3.0,NaN,NaN,NaN,0.766129,...,0.023355,0.001415,0.015667,0.007804,0.059091,23468.346154,17858.166667,0.509514,0.894841,0.719525
338,WI,2013,1.158434e+06,2.507937,2.238095,3.0,NaN,NaN,NaN,0.762020,...,0.021089,0.001334,0.017041,0.007925,0.059132,23945.597403,17789.870968,0.497656,0.892419,0.724933
339,WI,2014,1.202608e+06,2.605042,2.193277,3.0,NaN,NaN,NaN,0.750522,...,0.020953,0.001698,0.020109,0.008787,0.045622,24699.868421,17269.833333,0.499982,0.884368,0.708864
340,WI,2015,1.224190e+06,2.663793,2.172414,3.0,NaN,NaN,NaN,0.783024,...,0.022217,0.001830,0.023865,0.009594,0.037819,24804.710526,17956.925926,0.490283,0.871523,0.693885
341,WI,2016,1.226819e+06,2.663793,2.172414,3.0,43.624034,-88.887159,4.796460,0.765252,...,0.022494,0.001355,0.024821,0.010480,0.033854,25605.861111,18657.413793,0.482453,0.860326,0.666049
342,WV,2011,5.993892e+05,2.050000,1.825000,5.0,NaN,NaN,NaN,0.647132,...,0.003069,0.000840,0.005258,0.007162,0.023942,18644.140000,15496.035714,0.528488,0.798591,0.793942
343,WV,2012,6.039372e+05,2.115385,1.794872,5.0,NaN,NaN,NaN,0.641725,...,0.003788,0.001017,0.007751,0.008214,0.024864,18912.755102,11275.884615,0.563811,0.813497,0.790006
344,WV,2013,6.094382e+05,2.064935,1.792208,5.0,NaN,NaN,NaN,0.609733,...,0.002988,0.000575,0.007531,0.009108,0.020739,19307.553191,11579.769231,0.537467,0.804496,0.781031
345,WV,2014,6.061984e+05,2.088608,1.810127,5.0,NaN,NaN,NaN,0.628663,...,0.003226,0.000486,0.009776,0.010522,0.021275,19112.295455,13864.275862,0.582732,0.810227,0.777708
346,WV,2015,6.215248e+05,2.135135,1.810811,5.0,NaN,NaN,NaN,0.667743,...,0.003225,0.001048,0.014228,0.012566,0.022832,19842.714286,14485.692308,0.588323,0.801397,0.773473
347,WV,2016,6.230379e+05,2.120000,1.773333,5.0,38.882681,-80.697605,3.054054,0.721925,...,0.002715,0.000811,0.015153,0.011550,0.022251,20407.477273,14097.148148,0.540711,0.784126,0.757427
348,WY,2011,2.754009e+05,2.250000,1.666667,7.0,NaN,NaN,NaN,0.959000,...,0.022042,0.001558,0.006508,0.013558,0.014225,11077.500000,38926.000000,0.332345,0.706990,0.789694
349,WY,2012,2.754009e+05,2.250000,1.666667,7.0,NaN,NaN,NaN,0.953900,...,0.027275,0.001983,0.008583,0.010500,0.035500,12933.777778,18849.000000,0.349527,0.663972,0.814213
350,WY,2013,2.754009e+05,2.000000,1.666667,7.0,NaN,NaN,NaN,0.960100,...,0.022217,0.001900,0.011567,0.009975,0.045167,14181.200000,21976.500000,0.393242,0.681787,0.810989
351,WY,2014,2.598282e+05,2.181818,1.454545,7.0,NaN,NaN,NaN,0.956900,...,0.022355,0.002545,0.014845,0.011936,0.013473,13819.333333,22255.500000,0.362491,0.659713,0.785254
352,WY,2015,2.598282e+05,2.181818,1.454545,7.0,NaN,NaN,NaN,0.976600,...,0.021464,0.002818,0.017173,0.013482,0.025345,14171.333333,22489.000000,0.338827,0.642931,0.768001
353,WY,2016,2.598282e+05,2.181818,1.363636,7.0,42.283764,-106.315833,3.454545,0.956600,...,0.019545,0.004209,0.024691,0.016636,0.025009,14609.222222,22942.000000,0.315364,0.637638,0.744311

Delete non-summary irelevant columns for SchoolSummary data file

In [44]:
dfSchoolSummary.drop(['Unit ID', 'High Degree', 'Institution Type', 'Region ID', 'Latitude', 'Longitude',\
                      'Program Type', 'Enrollment'], axis=1, inplace=True)

Delete School records relating to 8 US Territories: "AS,FM,GU,MH,MP,PR,PW,VI"

In [45]:
USTerritoryList = ['AS','FM','GU','MH','MP','PR','PW','VI']

In [46]:
dfSchoolSummary = dfSchoolSummary[~(dfSchoolSummary['State'].isin(USTerritoryList))]
dfSchoolSummary.head(2)

,State,Year,Admission Rate,ACT Score,SAT Average,White,Black,Hispanic,Asian,American Indian/Alaska Native,Native Hawaiian/Pacific Islander,Multi-Racial,Non-Resident Aliens,Race Unknown,Attendance Cost - Academic Yr,Attendance Cost - Program Yr,Pell Grant Pct,Student Loan Pct,Pell Grant Award Pct
0,AK,2011,0.33285,23.0,1054.0,0.44190,0.028456,0.043056,0.04200,0.304122,0.008489,0.031544,0.007911,0.092556,18468.666667,11332.5,0.279056,0.753481,0.702259
1,AK,2012,0.34575,24.0,1077.0,0.48446,0.031400,0.038530,0.03794,0.286300,0.005490,0.029130,0.006330,0.080450,17199.000000,19440.0,0.304110,0.736423,0.717531

### Read in Population data set

In [47]:
dfPop = (pd.read_csv('Population.csv', header=0))
dfPop.head()

,Year,Total Population,White,Black,Hispanic,Male,Female
0,2010,"303,965,272","196,572,772","37,122,425","47,727,533","149,398,724","154,566,548"
1,2011,"306,603,772","196,730,055","37,449,666","49,215,563","150,740,216","155,863,556"
2,2012,"309,138,711","196,903,968","37,786,591","50,545,275","152,018,799","157,119,912"
3,2013,"311,536,594","197,050,418","38,093,998","51,786,591","153,247,412","158,289,182"
4,2014,"314,107,084","197,159,492","38,460,598","53,070,096","154,515,159","159,591,925"

Write data sets to file for Tableau upload

In [24]:
dfSchools.to_csv('SchoolData.csv')
dfSchoolSummary.to_csv('SchoolSummaryData.csv')
dfPop.to_csv('PopulationData.csv')